project:
  type: website
  output-dir: docs

website:
  title: "Ruairí Cullen"
  favicon: images/favicon-32x32.png
  navbar:
    logo: images/logo1.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects/index.qmd
        text: Projects
      - href: reflection.qmd
        text: BAA1104 Reflections
      - href: personal/personal.qmd
        text: Beyond the Desk 
    right:
      - href: contact.qmd
        text: Contact
      - href: cv/cv.pdf
        text: CV
        target: _blank
      - icon: github
        href: https://github.com/RuairiCullen
        target: _blank

  page-footer:
    left: "© 2026 Ruairí Cullen"
    right:
    - icon: github
      href: https://github.com/RuairiCullen
    - icon: linkedin
      href: https://www.linkedin.com/in/ruairi-c-02b268130/
    - icon: envelope
      href: mailto:ruairi.c12@gmail.com
    - icon: instagram
      href: https://www.instagram.com/ruairi.cullenn/
    center: "Built with [Quarto](https://quarto.org)"

format:
  html:
    theme:
      - lux
      - styles.scss
    fontsize: 1.1em
    linestretch: 1.7
    max-width: 900px
    fontcolor: "#1a3a2a"
    linkcolor: "#1a5c38"
    backgroundcolor: "#f0f7f2"
      
    css: styles.css
    toc: true



